name: 'Clean up PR staging content from composite target'
run-name: 'Clean up PR #${{github.event.pull_request.number}} from composite target'

on:
  pull_request_target:
    branches: [main]
    types: [closed]

env:
  TARGET_REPO: ${{ vars.COMPOSITE_TARGET_REPO }}
  TARGET_PATH: staging/${{ github.event.pull_request.number }}

concurrency:
  group: ci-ngiab-website-pr-#{{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  pr-clean-up:
    runs-on: ubuntu-latest
    environment:
      name: pr-staging
      url: https://ngiab.ciroh.org/${{ env.TARGET_PATH }}
    steps:
      - name: Set GitHub Actions as Commit Author
        run: |
          git config --global user.name github-actions
          git config --global user.email github-actions@github.com

      - name: Checkout staging repository
        uses: actions/checkout@v3
        with:
          repository: ${{ env.TARGET_REPO }}
          fetch-depth: 0
          path: "staging-deploy"
          ssh-key: ${{ secrets.SSH_DEPLOY_NGIAB_SUBDOMAIN }}
      
      - name: Remove PR folder from staging repository
        run: |
          cd staging-deploy
          git checkout gh-pages || git checkout --orphan gh-pages
          
          # Clear existing content
          git rm -rf ${{ env.TARGET_PATH }} || true
          
          git add .
          git commit -m "Remove staging folder for PR #${{ github.event.pull_request.number }} - ${{ github.sha }}" || echo "No changes to commit"
          git push -f origin gh-pages